Lab_1/Lab_1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls'))
]

Lab_1/todo/urls.py
from django.urls import path
from .views import index, get_task, delete_task, finish_task, edit_task, add_task

app_name = 'todo'

urlpatterns = [
    path('', index, name='index'),
    path('task/<int:task_id>', get_task, name='task_details'),
    path('task/finish/<int:task_id>', finish_task, name='task_finished'),
    path('task/edit/<int:task_id>', edit_task, name='task_edit'),
    path('task/delete/<int:task_id>', delete_task, name='task_delete'),
    path('task/add/', add_task, name='task_add'),

]

Lab_1/todo/models.py
from django.db import models

# Create your models here.


# class TaskModel(models.Model):
#     id = models.AutoField
#     name = models.CharField(max_length=30)
#     description = models.CharField(max_length=300)
#     is_done = models.AutoField

Lab_1/todo/forms.py
from django import forms


# creating a form
class TodoForm(forms.Form):
    name = forms.CharField(max_length=200)
    description = forms.CharField(max_length=200)

Lab_1/todo/views.py
import random

from django.shortcuts import render, HttpResponse, redirect, reverse
from django.http.response import JsonResponse
from pprint import pprint
from .forms import TodoForm

todo_list = [
    {'id': 1, 'name': 'breakfast', 'description': 'bla bla bla', 'is_done': False},
    {'id': 2, 'name': 'lecture', 'description': 'bla bla bla', 'is_done': True},
    {'id': 3, 'name': 'lab', 'description': 'bla bla bla', 'is_done': False}
]


def index(request, **kwargs):
    return render(request, 'todo/index.html', context={'list': todo_list, 'title': "Todo Tasks"})


def get_task(request, **kwargs):
    task = {}
    for item in todo_list:
        if item.get('id') == kwargs.get('task_id'):
            task = item
            # task = todo_list[todo_list.index(item)]
    print(f'Task: {task}')
    return render(request, 'todo/task_details.html', context={'task': task, 'title': 'Task Details'})


def add_task(request, **kwargs):
    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            print(form.data)
            todo_list.append({
                "id": random.randint(1, 999),
                "name": form.data.get('name'),
                "description": form.data.get('description'),
                "is_done": False,
            })
        return redirect(reverse('todo:index'))
    form = TodoForm()
    return render(request, "todo/task_form.html", {"form": form, "title": "Add new Task"})


def edit_task(request, **kwargs):
    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            for item in todo_list:
                if item.get('id') == kwargs.get('task_id'):
                    item.update({
                        "name": form.data.get('name'),
                        "description": form.data.get('description')
                    })
        return redirect(reverse('todo:index'))
    task = {}
    for item in todo_list:
        if item.get('id') == kwargs.get('task_id'):
            task = item
    # todo = list(filter(lambda n: n['id'] == kwargs.get('todo_id'), todos))[0]
    form = TodoForm(task)
    return render(request, "todo/task_form.html", {"form": form, "title": "Edit Task"})


def finish_task(request, **kwargs):
    for item in todo_list:
        if item.get('id') == kwargs.get('task_id'):
            item['is_done'] = True
    return redirect(reverse('todo:index'))


def delete_task(request, **kwargs):
    for item in todo_list:
        if item.get('id') == kwargs.get('task_id'):
            todo_list.remove(item)
            # todo_list.pop(todo_list.index(item))
    return redirect(reverse('todo:index'))
    # return render(request, 'todo/index.html', context={'list': todo_list})

Lab_1/templates/general_templates/base.html
{% load static %}
{% load custom_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
    <div class="container-md d-flex justify-content-start">
        <span class="navbar-brand mb-0 h1 fs-1 pe-3">ITI Todo List</span>
        <div class="btn-group" role="group" aria-label="Basic mixed styles example">
            <a type="button" class="btn btn-primary" href="{% url 'todo:index' %}">All tasks</a>
            <a type="button" class="btn btn-success" href="{% url 'todo:task_add' %}">Add Task +</a>
        </div>
    </div>
</nav>
<div class="container">
{% weather_template_tag as weather %}
    <h3>Weather API template:</h3>
    {{ weather }}
    {% block body_content %}

    {% endblock %}
</div>
<script src="{% static 'js/boostrap.bundle.min.js' %}"></script>
</body>
</html>

Lab_1/todo/templates/todo/index.html
{% extends 'general_templates/base.html' %}
{% block title %} {{ title }} {% endblock %}

{% block body_content %}

<div class="mt-5 ">
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Status</th>
            <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody class="table-group-divider">
        {% for task in list %}
        <tr>
            <th scope="row">{{ task.id }}</th>
            <td>{{ task.name|title }}</td>
            <td>{{ task.description }}</td>
            {% if task.is_done == False %}
            <td>Pending...</td>
            {% else %}
            <td>Finished &#10004;</td>
            {% endif %}
            <td>
                {% if task.is_done == True %}
                <a class="btn btn-success disabled" href="{% url 'todo:task_finished' task.id %}">Mark Done</a>
                {% else %}
                <a class="btn btn-success" href="{% url 'todo:task_finished' task.id %}">Mark Done</a>
                {% endif %}
                <a class="btn btn-primary" href="{% url 'todo:task_details' task.id %}">View</a>
                <a class="btn btn-secondary" href="{% url 'todo:task_edit' task.id %}">Edit</a>
                {% if task.is_done == False %}
                <a class="btn btn-danger disabled">Delete</a>
                {% else %}
                <a class="btn btn-danger" href="{% url 'todo:task_delete' task.id %}">Delete</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

Lab_1/todo/templates/todo/task_details.html
{% extends 'general_templates/base.html' %}
{% block title %} {{ title }} {% endblock %}
{% block body_content %}

<div class="container mt-5 col-8">
    <div class="card border-dark mb-3">
        <div class="card-header">Task Info</div>
        <div class="card-body text-dark">
        <h5 class="card-title fs-6 fw-bold">Name:</h5>
        <p class="card-text">{{ task.name }}</p>
        <h5 class="card-title fs-6 fw-bold">Description:</h5>
        <p class="card-text">{{ task.description }}</p>
        <h5 class="card-title fs-6 fw-bold">Status:</h5>
        {% if task.is_done == False %}
            <p class="card-text">Pending</p>
        {% else %}
            <p class="card-text">Finished</p>
        {% endif %}
        </div>
    </div>
</div>

{% endblock %}

Lab_1/todo/templates/todo/task_form.html
{% extends 'general_templates/base.html' %}
{% block title %} {{ title }} {% endblock %}
{% block body_content %}

<form class="g-3 m-3" action = "" method = "post">
    {% csrf_token %}
    <div class="col-md-6 mb-3">
        {{ form }}
    </div>
    <div>
    <button class="btn btn-secondary" type="reset">Clear</button>
        {% if title == 'Edit Task' %}
    <button class="btn btn-success" type="submit">Update</button>
        {% else %}
    <button class="btn btn-success" type="submit">Add</button>
        {% endif %}
    </div>
</form>

{% endblock %}